version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: TEST-Eukles-db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    volumes:
      - './Databases:/var/lib/mysql'
  myapp:
    image: docker.io/bitnami/laravel:8
    container_name: TEST-Eukles-app
    ports:
      - '8070:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
